"""
Lecture 2.5: Trade-offs and Challenges of Event-Based Processing
"""

# ------------------
# Challenge 1: Noise

"""
Event-based sensors have a complex noise profile.
The consequence is that event-based algorithms must
explicitly handle noise — through temporal filtering
(discarding events that occur in isolation, without
neighboring events at similar times), spatial filtering
(requiring correlated events across adjacent pixels),
or statistical methods that treat the event stream as a
noisy channel. This adds algorithmic complexity.
"""

# ----------------------------------------
# Challenge 2: No Texture in Static Scenes

"""
If you want to recognize a stationary object,
the raw event stream gives you nothing.
"""

# ---------------------------------
# Challenge 3: Algorithm Complexity

"""
This means that working with event-based data today
requires mastering a more diverse and less mature algorithmic
toolkit than frame-based vision — a genuine challenge for practitioners.
"""

# ----------------------------------------
# Challenge 4: Evaluation and Benchmarking

"""
The field has developed event-based datasets — the N-MNIST,
N-Caltech101, and DSEC driving datasets, among others
— but these are still far smaller and less diverse than the
large-scale frame-based datasets that have driven deep learning progress.
"""

# ..............................................................
# Worked Example: When to Use Event-Based vs. Frame-Based Vision

# Task 1: Counting pedestrians entering a store entrance over an 8-hour period.
"""
Scene: Mostly static. Pedestrians slowly walk past a camera that is fixed to a wall.
Frame-based is likely better. The motion events generated by pedestrians would
be useful, but texture and shape information (which event cameras can’t provide
in static moments) matter for accurately distinguishing people.
"""

# Task 2: Tracking a drone flying at 80 km/h through an obstacle course.
"""
Highly dynamic. Fast motion, changing lighting, millisecond-level events critical.
Event-based is better. The drone generates strong, fast edge events.
Latency below 1 ms is achievable.
"""

# Task 3: Reading a license plate on a parked car in a parking garage.
"""
Frame-based is clearly better. The event camera would produce zero events
for a parked car in static illumination.
"""
