"""
Lecture 9.6: Training a Neural Network on Neural Data

In the previous lectures, you used clean synthetic datasets
generated by make_classification. However, real neural data
is never clean.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

# import seaborn as sns  # optional, for nicer heatmap

np.random.seed(42)
tf.random.set_seed(42)

# Simulate spike waveform features from 3 sessions
# Features per spike:
#   [peak_amplitude, trough_depth, half_width, rise_time,
#    decay_time, peak_to_trough_ratio, AHP_amplitude, ISI_mean]


def simulate_session(n_spikes, session_quality, neuron_type, rng):
    """
    Simulate spike waveform feature vectors for one neuron type in one session.
    session_quality (0.5 - 1.0) models electrode drift — lower quality
    adds more noise and scales amplitude down slightly.
    """
    # Base waveform parameters per neuron type
    base_params = {
        "FS": [180, -90, 0.45, 0.2, 0.3, 2.0, -12, 40],  # Fast-spiking
        "RS": [120, -40, 0.85, 0.4, 0.7, 3.0, -5, 80],  # Regular-spiking
        "IB": [100, -50, 0.90, 0.5, 0.9, 2.1, -7, 25],  # Intrinsically bursting
    }
    noise_scale = {
        "FS": [15, 8, 0.05, 0.03, 0.05, 0.2, 1.5, 10],
        "RS": [12, 5, 0.08, 0.05, 0.08, 0.3, 1.0, 15],
        "IB": [14, 6, 0.09, 0.06, 0.10, 0.3, 1.2, 8],
    }
    base = np.array(base_params[neuron_type])
    noise = np.array(noise_scale[neuron_type])

    spikes = rng.normal(base, noise, size=(n_spikes, 8))

    # Apply session quality degradation (electrode drift simulation)
    amplitude_scale = session_quality + rng.normal(0, 0.05)
    spikes[:, 0] *= amplitude_scale
    spikes[:, 1] *= amplitude_scale
    spikes += rng.normal(0, (1 - session_quality) * 8, size=spikes.shape)

    return spikes


rng = np.random.default_rng(42)

# Simulate 3 recording sessions with different electrode quality
all_data = []
label_names = {"FS": 0, "RS": 1, "IB": 2}

session_configs = [
    (1, 0.95, {"FS": 120, "RS": 200, "IB": 80}),  # Session 1: good quality
    (2, 0.75, {"FS": 90, "RS": 180, "IB": 60}),  # Session 2: moderate drift
    (3, 0.85, {"FS": 100, "RS": 160, "IB": 70}),  # Session 3: good quality
]

for session_id, quality, counts in session_configs:
    for neuron_type, n in counts.items():
        spikes = simulate_session(n, quality, neuron_type, rng)
        df = pd.DataFrame(
            spikes,
            columns=[
                "peak_amp",
                "trough_depth",
                "half_width",
                "rise_time",
                "decay_time",
                "pt_ratio",
                "AHP_amp",
                "ISI_mean",
            ],
        )
        df["neuron_type"] = neuron_type
        df["label"] = label_names[neuron_type]
        df["session"] = session_id
        all_data.append(df)

data = pd.concat(all_data, ignore_index=True)
print(f"Total spikes: {len(data)}")
print("\nClass distribution:")
print(data["neuron_type"].value_counts())
print("\nSession distribution:")
print(data.groupby(["session", "neuron_type"]).size().unstack(fill_value=0))
print()

# --------------------------------------------
# Preprocessing: Handling Real Data Challenges

# Step 1: Check for and handle missing values
print(f"\nMissing values:\n{data.isnull().sum()}")

# Step 2: Check for physiologically implausible values (artifacts)
feature_cols = [
    "peak_amp",
    "trough_depth",
    "half_width",
    "rise_time",
    "decay_time",
    "pt_ratio",
    "AHP_amp",
    "ISI_mean",
]

# Flag spikes with extreme values (> 4 std from mean) as potential artifacts
z_scores = np.abs((data[feature_cols] - data[feature_cols].mean()) / data[feature_cols].std())

artifact_mask = (z_scores > 4).any(axis=1)
print(f"\nPotential artifact spikes (>4 SD from mean): {artifact_mask.sum()}")
data_clean = data[~artifact_mask].copy()
print(f"Spikes after artifact rejection: {len(data_clean)}")

# Step 3: Visualize feature distributions across sessions
fig, axes = plt.subplots(2, 4, figsize=(14, 6))
axes = axes.flatten()

for i, col in enumerate(feature_cols):
    for session_id in [1, 2, 3]:
        session_data = data_clean[data_clean["session"] == session_id][col]
        axes[i].hist(session_data, bins=25, alpha=0.5, label=f"Session {session_id}", density=True)
    axes[i].set_title(col.replace("_", " ").title(), fontsize=9)
    axes[i].tick_params(labelsize=7)
    if i == 0:
        axes[i].legend(fontsize=7)

plt.suptitle("Feature Distributions Across Sessions\n(pre-normalization)", fontweight="bold")
plt.tight_layout()
plt.savefig("figure_9-6_feature_distributions.png", dpi=150)

# Step 4: Prepare feature matrix and labels
X = data_clean[feature_cols].values
y = data_clean["label"].values

print(f"\nFeature matrix: {X.shape}")
print(f"Label vector:   {y.shape}")

# Step 5: Train-test split BEFORE scaling
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Step 6: Scale using training statistics only
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

print(f"\nTraining set: {X_train_s.shape}")
print(f"Test set:     {X_test_s.shape}")

# Verify scaling
print("\nTraining features after scaling:")
print(f"  Mean: {X_train_s.mean(axis=0).round(3)}")  # Should be ~0
print(f"  Std:  {X_train_s.std(axis=0).round(3)}")  # Should be ~1
print()

# ------------------------------------
# Building the Network for Neural Data

# Network architecture designed for 8 electrophysiology features
# and ~900 training examples


def build_neuron_classifier(n_features, n_classes, dropout_rate=0.3):
    """
    Build a compact fully-connected network for spike waveform classification.

    Architecture rationale:
    - 64 units in first hidden layer: ~8x the input, room to learn combinations
    - 32 units in second: compression forces meaningful representation
    - Dropout between each layer: prevents co-adaptation of neurons
    - ~2,700 total parameters: appropriate for ~900 training examples
    """
    model = keras.Sequential(
        [
            keras.Input(shape=(n_features,)),
            layers.Dense(64, activation="relu"),
            layers.BatchNormalization(),  # Normalize activations, stabilizes training
            layers.Dropout(dropout_rate),
            layers.Dense(32, activation="relu"),
            layers.BatchNormalization(),
            layers.Dropout(dropout_rate * 0.7),
            layers.Dense(n_classes, activation="softmax"),
        ],
        name="neuron_type_classifier",
    )

    return model


model = build_neuron_classifier(n_features=8, n_classes=3)
model.summary()

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)
print()

# -----------------------
# Training and Monitoring

early_stopping = EarlyStopping(
    monitor="val_accuracy", patience=20, restore_best_weights=True, verbose=1
)

history = model.fit(
    X_train_s,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.15,
    callbacks=[early_stopping],
    verbose=0,
)

print(f"Stopped at epoch {len(history.history['loss'])}")
print(f"Best val accuracy: {max(history.history['val_accuracy']):.1%}")
# Plot training curves
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, metric, ylabel in zip(
    axes, [("loss", "val_loss"), ("accuracy", "val_accuracy")], ["Loss (cross-entropy)", "Accuracy"]
):
    ax.plot(history.history[metric[0]], color="#3498db", linewidth=2, label="Training")
    ax.plot(history.history[metric[1]], color="#e74c3c", linewidth=2, label="Validation")
    ax.set_xlabel("Epoch")
    ax.set_ylabel(ylabel)
    ax.set_title(f"Training vs Validation {ylabel}")
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.suptitle("Network Training: Neuron Type Classifier", fontweight="bold")
plt.tight_layout()
plt.savefig("figure_9-6_nn_training_curves.png", dpi=150)
print()

# --------------------------------------
# Final evaluation — the moment of truth

test_loss, test_accuracy = model.evaluate(X_test_s, y_test, verbose=0)
print(f"Test accuracy: {test_accuracy:.1%}")

y_pred_proba = model.predict(X_test_s, verbose=0)
y_pred = np.argmax(y_pred_proba, axis=1)

neuron_labels = ["Fast-spiking (FS)", "Regular-spiking (RS)", "Intrinsically Bursting (IB)"]

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=neuron_labels))
# Confusion matrix — visualize where the mistakes happen
cm = confusion_matrix(y_test, y_pred)

fig, ax = plt.subplots(figsize=(6, 5))
im = ax.imshow(cm, cmap="Blues")
plt.colorbar(im, ax=ax)

ax.set_xticks(range(3))
ax.set_yticks(range(3))
ax.set_xticklabels(["FS", "RS", "IB"], fontsize=11)
ax.set_yticklabels(["FS", "RS", "IB"], fontsize=11)
ax.set_xlabel("Predicted neuron type", fontsize=12)
ax.set_ylabel("True neuron type", fontsize=12)
ax.set_title("Confusion Matrix: Neuron Type Classification", fontweight="bold")

for i in range(3):
    for j in range(3):
        text_color = "white" if cm[i, j] > cm.max() * 0.5 else "black"
        ax.text(
            j,
            i,
            str(cm[i, j]),
            ha="center",
            va="center",
            color=text_color,
            fontsize=14,
            fontweight="bold",
        )

plt.tight_layout()
plt.savefig("figure_9-6_confusion_matrix.png", dpi=150)
print()

# -------------------------------------
# Prediction Confidence and Uncertainty

# Examine prediction confidence
confidence = np.max(y_pred_proba, axis=1)

correct_mask = y_pred == y_test
print("Prediction confidence analysis:")
print(f"  Mean confidence (correct):   {confidence[correct_mask].mean():.3f}")
print(f"  Mean confidence (incorrect): {confidence[~correct_mask].mean():.3f}")

# Low-confidence predictions are candidates for manual review
low_confidence_threshold = 0.6
n_low_conf = (confidence < low_confidence_threshold).sum()
print(f"\nSpikes with confidence < {low_confidence_threshold}: {n_low_conf}")
print("These could be multi-unit activity, unusual firing patterns,")
print("or recording artifacts that escaped preprocessing.")

# This is standard practice in spike sorting workflows:
# automated classification handles the high-confidence cases,
# and a human expert reviews the uncertain ones
